<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>FileMetadataStripping</AssemblyName>
    <RootNamespace>OutSystems.NssFileMetadataStripping</RootNamespace>
    <LangVersion>10</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.15.0" />
    <PackageReference Include="OpenMcdf" Version="3.1.4" />
    <PackageReference Include="OpenMcdf.Ole" Version="3.1.4-experimental.1" />
    <PackageReference Include="PDFsharp" Version="1.50.5147" />
    <PackageReference Include="System.IO.Packaging" Version="8.0.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

</Project>
