namespace OutSystems.NssFileMetadataStripping;

/// <summary>
/// Interface generated by Integration Studio for the FileMetadataStripping extension.
/// Do not edit — regenerated when the extension definition changes in Integration Studio.
/// </summary>
public interface IssFileMetadataStripping
{
    void MssStripFileMetadata(byte[] ssRawFile, out RecFileMetadataResult ssStripFileMetadata);
}
