namespace OutSystems.NssFileMetadataStripping;

/// <summary>
/// Maps to the FileMetadataResult Structure defined in Integration Studio.
/// Field names use the ss-prefix convention generated by Integration Studio.
/// </summary>
public struct RecFileMetadataResult
{
    public byte[]  ssCleanFile;
    public string  ssExtractedMetadata;
    public int     ssRemovedEntryCount;
    public bool    ssIsPassthrough;
}
